# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default=b' ', max_length=255),
        ),
    ]
