# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.SlugField(blank=True, max_length=255, verbose_name=b'url'),
        ),
    ]
