# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-12 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default=b' ', upload_to=b'images/'),
        ),
    ]
